from typing import Dict, Any, List

# ============================================================
# PLACEHOLDER — GenAI Application Layer Adapter
# These functions are integration-ready stubs.
# Final explanation/summarization intelligence TBD.
# ============================================================

def generate_explanation(plan_result: Dict[str, Any]) -> str:
    """
    PLACEHOLDER: Convert plan output into human-readable explanation.
    Integration point for Gemini / LLM-based explanation logic.
    """
    selected = plan_result.get("selected_trains", [])
    total = plan_result.get("total_trains", len(plan_result.get("details", [])))
    conf = plan_result.get("confidence_score", 0)
    return (
        f"[PLACEHOLDER] The system identified {len(selected)} trains as ready for induction out of {total} evaluated. "
        f"This decision is based on maintenance readiness, fitness certificate compliance, and penalty risk levels. "
        f"Placeholder confidence score: {conf}. "
        f"Final explanation will be generated by the GenAI layer once the core optimizer output is integrated."
    )


def explain_plan(plan_data: Dict[str, Any]) -> str:
    """
    PLACEHOLDER: Generate a rich explanation for a persisted plan.
    Integration point for GenAI/LLM layer.
    """
    details = plan_data.get("details", [])
    inducted = [d for d in details if d.get("decision") == "INDUCT"]
    held = [d for d in details if d.get("decision") == "HOLD"]
    overrides = [d for d in details if d.get("override_flag")]
    return (
        f"[PLACEHOLDER] Plan summary: {len(inducted)} trains inducted, {len(held)} held. "
        f"{len(overrides)} manual override(s) applied. "
        f"Full AI-driven explanation will be available once the GenAI integration layer is connected."
    )


def summarize_plan(plan_data: Dict[str, Any]) -> Dict[str, Any]:
    """
    PLACEHOLDER: Produce a structured summary dict for a persisted plan.
    Integration point for GenAI layer.
    """
    details = plan_data.get("details", [])
    inducted = [d for d in details if d.get("decision") == "INDUCT"]
    held = [d for d in details if d.get("decision") == "HOLD"]
    overrides = [d for d in details if d.get("override_flag")]
    return {
        "total": len(details),
        "inducted": len(inducted),
        "held": len(held),
        "overrides": len(overrides),
        "note": "PLACEHOLDER — final GenAI summary pending integration",
    }


def generate_role_summary(role: str, data: Dict[str, Any]) -> str:
    """
    PLACEHOLDER: Role-specific GenAI summary.
    """
    return f"[PLACEHOLDER] {role} summary: All key parameters are within acceptable limits. GenAI layer pending."


def ask_assistant(query: str, context: Dict[str, Any]) -> str:
    """
    PLACEHOLDER: Planner assistant query handler.
    Integration point for a RAG/LLM assistant.
    """
    query_lower = query.lower()
    if "why" in query_lower and "not selected" in query_lower:
        return "[PLACEHOLDER] The train was not selected due to failing maintenance or fitness criteria. Full reasoning will be provided by the AI assistant once integrated."
    elif "highest" in query_lower and "risk" in query_lower:
        return "[PLACEHOLDER] Branding SLA risk is highest for trains with low accumulated exposure hours. Exact ranking will come from the optimizer."
    elif "lock" in query_lower:
        return "[PLACEHOLDER] Locking a plan freezes all decisions. Overrides must be applied before locking."
    else:
        return "[PLACEHOLDER] I am the MetroFlow GenAI Assistant. I will provide intelligent operational explanations once the core AI layer is integrated. Your query: \"" + query + "\""
